function save(obj, filename)
[lambda, nfeatures, mus, sigs, lassoCoeffs, biasTerm, pdPos, pdNeg, priorPos, priorNeg, predictorNames, trainingCvguids, calCorrection] = deal( ...
    obj.lambda, obj.nfeatures, obj.mus, obj.sigs, obj.lassoCoeffs, ...
    obj.biasTerm, obj.pdPos, obj.pdNeg, obj.priorPos, obj.priorNeg, obj.predictorNames, obj.trainingCvguids, obj.calCorrection);
save(filename, 'lambda', 'nfeatures', 'mus', 'sigs', ...
    'lassoCoeffs', 'biasTerm', 'pdPos', 'pdNeg', 'priorPos', 'priorNeg', 'predictorNames', 'trainingCvguids', 'calCorrection');
